### ISSUE TITLE
ACEX Sitting Module

### ISSUE THREAD

**Issue by Astronautics** [RSpeekenbrink/A3_15thMEU_H2Missions#1]
Cpl Speekenbrink,

The Sitting Module is not set on the server. Please add sitting and those super sexy swivel chairs that don't actually swivel but make us look G as fuck.

Thank you in advance, Mister Speekenbrink.

Fair winds and following memes,

FaZe Mooney

**Comment by RSpeekenbrink** [comment]
Added in #e863ab3
